service: NAME_LAMBDA
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  stage: dev
  environment:
    TABLE_NAME: ${env:TABLE_NAME}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    REGION: ${env:REGION}
functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: /teste
          method: POST

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
